name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Build and push Docker image
        run: |
          docker build -t sandramsc/docverifyrag:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push sandramsc/docverifyrag:latest
