name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/docverifyrag

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/docverifyrag
